export const dialDataArrayRx = [
  {
    model: "610",
    dials: [],
  },
  {
    model: "620",
    dials: [],
  },
  {
    model: "4233",
    dials: ["BLACK"],
  },
  {
    model: "6239",
    dials: [],
  },
  {
    model: "6241",
    dials: [],
  },
  {
    model: "6262",
    dials: [],
  },
  {
    model: "6263",
    dials: [],
  },
  {
    model: "6264",
    dials: [],
  },
  {
    model: "6265",
    dials: [],
  },
  {
    model: "6280",
    dials: [],
  },
  {
    model: "6291",
    dials: [],
  },
  {
    model: "16520",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "16623",
    dials: ["CHAMPAGNE", "WHITE", "STEEL", "BLUE", "BLACK MOP"],
  },
  {
    model: "18946",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
      "ICE BLUE",
    ],
  },
  {
    model: "18948",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "52508",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "52509",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "67480",
    dials: [],
  },
  {
    model: "67490",
    dials: [],
  },
  {
    model: "67580",
    dials: [],
  },
  {
    model: "80285",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "STEEL ROMAN",
      "PINK",
      "PINK ROMAN",
      "PINK ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE MOP LOTUS FLOWER MOTIF VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "METEORITE DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "80298",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "80299",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "80315",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "STEEL ROMAN",
      "PINK",
      "PINK ROMAN",
      "PINK ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE MOP LOTUS FLOWER MOTIF VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "METEORITE DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "80318",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "80319",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "81158",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "81159",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "81298",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "81299",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "81315",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "PINK",
      "PINK ROMAN",
      "PINK FLORAL MOTIF ARABIC 6",
      "PURPLE ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "81318",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "81319",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "81338",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "81339",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "114060",
    dials: ["BLACK"],
  },
  {
    model: "114200",
    dials: [
      "WHITE ARABICIC",
      "SILVER ARABICIC",
      "PINK ARABICIC",
      "BLUE ARABICIC",
    ],
  },
  {
    model: "114300",
    dials: ["BLACK", "BLUE", "SLATE", "RED GRAPE", "WHITE"],
  },
  {
    model: "115200",
    dials: ["WHITE", "SILVER", "PINK", "BLUE", "BLACK"],
  },
  {
    model: "115234",
    dials: [
      "WHITE",
      "SILVER",
      "PINK",
      "BLUE",
      "BLACK",
      "WHITE 5 ARABICIC 5 DIAMOND",
      "SILVER 5 ARABICIC 5 DIAMOND",
      "PINK 5 ARABICIC 5 DIAMOND",
      "BLACK 5 ARABICIC 5 DIAMOND",
    ],
  },
  {
    model: "116000",
    dials: ["BLACK", "BLUE", "RED GRAPE", "STEEL", "WHITE", "WHITE GRAPE"],
  },
  {
    model: "116070",
    dials: [],
  },
  {
    model: "116135",
    dials: [
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "STEEL ROMAN",
      "STEEL DIAMOND",
      "PINK",
      "PINK ROMAN",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "CHOCOLATE FLORAL MOTIF ARABICIC 6-9 DIAMOND",
      "BLACK DIAMOND",
      "BLACK JUBILEE DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "116200",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DECORATED ARABICIC",
      "SILVER FLORAL MOTIF ARABICIC",
      "PINK",
      "PINK FLORAL MOTIF ARABICIC",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BRONZE FLORAL MOTIF ARABICIC",
    ],
  },
  {
    model: "116201",
    dials: [
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "STEEL ROMAN",
      "STEEL DIAMOND",
      "PINK",
      "PINK ROMAN",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "CHOCOLATE FLORAL MOTIF ARABICIC 6-9 DIAMOND",
      "BLACK DIAMOND",
      "BLACK JUBILEE DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "116203",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "IVORY ROMAN PYR",
      "SILVER FLORAL MOTIF ARABICIC",
      "STEEL ROMAN",
      "GREEN FLORAL MOTIF ARABICIC",
      "BLACK",
      "BLACK ROMAN JUBILEE",
      "BRONZE ARABICIC",
      "BRONZE FLORAL MOTIF ARABICIC",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE DIAMOND",
      "SILVER DIAMOND",
    ],
  },
  {
    model: "116231",
    dials: [
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "STEEL ROMAN",
      "STEEL DIAMOND",
      "PINK",
      "PINK ROMAN",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "CHOCOLATE FLORAL MOTIF ARABICIC 6-9 DIAMOND",
      "BLACK DIAMOND",
      "BLACK JUBILEE DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "116233",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "IVORY ROMAN PYR",
      "SILVER FLORAL MOTIF ARABICIC",
      "STEEL ROMAN",
      "GREEN FLORAL MOTIF ARABICIC",
      "BLACK",
      "BLACK ROMAN JUBILEE",
      "BRONZE ARABICIC",
      "BRONZE FLORAL MOTIF ARABICIC",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE DIAMOND",
      "SILVER DIAMOND",
    ],
  },
  {
    model: "116234",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DECORATED ARABICIC",
      "SILVER FLORAL MOTIF ARABICIC",
      "PINK",
      "PINK FLORAL MOTIF ARABICIC",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BRONZE FLORAL MOTIF ARABICIC",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM WAVES ARABICIC DIAMOND",
    ],
  },
  {
    model: "116238",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "IVORY ROMAN PYR",
      "SILVER FLORAL MOTIF ARABICIC",
      "STEEL ROMAN",
      "GREEN FLORAL MOTIF ARABICIC",
      "BLACK",
      "BLACK ROMAN JUBILEE",
      "BRONZE ARABICIC",
      "BRONZE FLORAL MOTIF ARABICIC",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE DIAMOND",
      "SILVER DIAMOND",
    ],
  },
  {
    model: "116243",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "IVORY ROMAN PYR",
      "SILVER FLORAL MOTIF ARABICIC",
      "STEEL ROMAN",
      "GREEN FLORAL MOTIF ARABICIC",
      "BLACK",
      "BLACK ROMAN JUBILEE",
      "BRONZE ARABICIC",
      "BRONZE FLORAL MOTIF ARABICIC",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE DIAMOND",
      "SILVER DIAMOND",
    ],
  },
  {
    model: "116244",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DECORATED ARABICIC",
      "SILVER FLORAL MOTIF ARABICIC",
      "PINK",
      "PINK FLORAL MOTIF ARABICIC",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BRONZE FLORAL MOTIF ARABICIC",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM WAVES ARABICIC DIAMOND",
    ],
  },
  {
    model: "116300",
    dials: [
      "WHITE",
      "SILVER",
      "RHODIUM ARABICIC",
      "BLUE",
      "BLUE AZZURO ROMAN",
      "BLACK",
      "BLACK ROMAN",
    ],
  },
  {
    model: "116333",
    dials: [
      "WHITE",
      "SILVER",
      "RHODIUM ARABICIC",
      "BLUE",
      "BLUE AZZURO ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "IVORY",
      "IVORY DIAMOND",
      "SLATE ROMAN",
      "BLACK ROMAN",
      "BLACK ARABICIC",
    ],
  },
  {
    model: "116334",
    dials: [
      "WHITE",
      "SILVER",
      "RHODIUM ARABICIC",
      "BLUE",
      "BLUE AZZURO ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "SILVER DIAMOND",
      "DARK RHODIUM DIAMOND",
    ],
  },
  {
    model: "116400",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "116503",
    dials: [
      "BLACK",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "WHITE",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "116505",
    dials: [
      "CHOCOLATE",
      "WHITE",
      "BLACK",
      "CHOCOLATE ARABICIC",
      "SUNDUST",
      "SUNDUST DIAMOND",
      "METEORITE",
      "IVORY",
      "PINK/BLACK",
      "BLACK/PINK",
    ],
  },
  {
    model: "116506",
    dials: ["ICE BLUE", "ICE BLUE DIAMOND"],
  },
  {
    model: "116508",
    dials: [
      "GREEN",
      "BLACK",
      "BLACK DIAMOND",
      "BLACK/CHAMPAGNE",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE/BLACK",
      "WHITE",
      "BLACK MOP DIAMOND",
      "WHITE MOP DIAMOND",
      "STEEL",
      "METEORITE",
      "BLUE ARABICIC",
    ],
  },
  {
    model: "116509",
    dials: [
      "BLUE",
      "SODALITE",
      "BLACK",
      "BLACK DIAMOND",
      "BLACK ARABICIC",
      "SILVER ARABICIC",
      "DARK GREY ARABICIC",
      "STEEL",
      "METEORITE",
      "METEORITE ROMAN",
      "WHITE MOP DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "116518",
    dials: [
      "BLACK",
      "BLACK DIAMOND",
      "BLACK/CHAMPAGNE",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE/BLACK",
      "METEORITE",
      "WHITE",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "116519",
    dials: ["PANDA", "WHITE MOP DIAMOND", "BLUE ENAMEL PAVE ARABICIC"],
  },
  {
    model: "116520",
    dials: ["WHITE", "BLACK"],
  },
  {
    model: "116523",
    dials: [
      "BLACK",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "WHITE",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "METEORITE",
      "BLUE ARABICIC",
    ],
  },
  {
    model: "116528",
    dials: [
      "BLUE ARABICIC",
      "BLACK",
      "BLACK DIAMOND",
      "BLACK/CHAMPAGNE",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE/BLACK",
      "PANDA",
      "BLACK MOP DIAMOND",
      "WHITE MOP DIAMOND",
      "WHITE",
      "WHITE DIAMOND",
      "STEEL",
    ],
  },
  {
    model: "116599",
    dials: [
      "METEORITE ROMAN",
      "BLACK ENAMEL PAVE ARABICIC",
      "PINK MOP DIAMOND",
      "SLATE ARABICIC",
      "BLUE ENAMEL PAVE ROMAN",
      "BLACK DIAMOND",
      "GOLD CRYSTAL DIAMOND",
      "BLACK ENAMEL PAVE ROMAN",
    ],
  },
  {
    model: "116600",
    dials: ["BLACK"],
  },
  {
    model: "116622",
    dials: ["SLATE", "BLUE", "PLATINUM"],
  },
  {
    model: "116655",
    dials: ["BLACK", "PAVE DIAMOND"],
  },
  {
    model: "116660",
    dials: ["BLACK", "D-BLUE"],
  },
  {
    model: "116680",
    dials: ["WHITE"],
  },
  {
    model: "116681",
    dials: ["WHITE"],
  },
  {
    model: "116688",
    dials: ["WHITE"],
  },
  {
    model: "116689",
    dials: ["WHITE"],
  },
  {
    model: "116900",
    dials: ["BLACK"],
  },
  {
    model: "118135",
    dials: [
      "WHITE ROMAN",
      "RHODIUM",
      "PINK ROMAN",
      "CHOCOLATE",
      "BLACK",
      "BLACK ARABICIC",
      "WHITE MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "CAROUSEL OF PINK MOP DIAMOND",
      "CHOCOLATE 8 DIAMOND 2 RUBIES",
      "BLACK MOP DIAMOND",
      "FERRITE DIAMOND",
    ],
  },
  {
    model: "118138",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118139",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "118205",
    dials: [
      "WHITE ROMAN",
      "RHODIUM",
      "PINK ROMAN",
      "CHOCOLATE",
      "BLACK",
      "BLACK ARABICIC",
      "WHITE MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "CAROUSEL OF PINK MOP DIAMOND",
      "CHOCOLATE 8 DIAMOND 2 RUBIES",
      "BLACK MOP DIAMOND",
      "FERRITE DIAMOND",
    ],
  },
  {
    model: "118206",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
      "ICE BLUE",
    ],
  },
  {
    model: "118208",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118235",
    dials: [
      "WHITE ROMAN",
      "RHODIUM",
      "PINK ROMAN",
      "CHOCOLATE",
      "BLACK",
      "BLACK ARABICIC",
      "WHITE MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "CAROUSEL OF PINK MOP DIAMOND",
      "CHOCOLATE 8 DIAMOND 2 RUBIES",
      "BLACK MOP DIAMOND",
      "FERRITE DIAMOND",
    ],
  },
  {
    model: "118238",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118239",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "118296",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
      "ICE BLUE",
    ],
  },
  {
    model: "118338",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118339",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "118346",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
      "ICE BLUE",
    ],
  },
  {
    model: "118348",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118366",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
      "ICE BLUE",
    ],
  },
  {
    model: "118388",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118389",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "118395",
    dials: [
      "WHITE ROMAN",
      "RHODIUM",
      "PINK ROMAN",
      "CHOCOLATE",
      "BLACK",
      "BLACK ARABICIC",
      "WHITE MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "CAROUSEL OF PINK MOP DIAMOND",
      "CHOCOLATE 8 DIAMOND 2 RUBIES",
      "BLACK MOP DIAMOND",
      "FERRITE DIAMOND",
    ],
  },
  {
    model: "118398",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "118399",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "124060",
    dials: ["BLACK"],
  },
  {
    model: "124200",
    dials: ["BLACK", "BLUE", "PINK", "SILVER"],
  },
  {
    model: "124270",
    dials: ["BLACK"],
  },
  {
    model: "124273",
    dials: ["BLACK"],
  },
  {
    model: "124300",
    dials: [
      "BLACK",
      "BLUE",
      "SILVER",
      "GREEN",
      "CELEBRATION",
      "TURQUOISE",
      "CORAL RED",
      "YELLOW",
    ],
  },
  {
    model: "126000",
    dials: [
      "BLACK",
      "BLUE",
      "SILVER",
      "GREEN",
      "TURQUOISE",
      "CANDY PINK",
      "CELEBRATION",
      "CORAL RED",
      "YELLOW",
    ],
  },
  {
    model: "126067",
    dials: ["BLACK"],
  },
  {
    model: "126200",
    dials: [
      "BLACK",
      "WIMBLEDON",
      "BLUE",
      "GREEN",
      "SILVER",
      "WHITE ROMAN",
      "BLUE FLUTED",
      "GREEN PALM",
    ],
  },
  {
    model: "126201",
    dials: [
      "SLATE",
      "WIMBLEDON",
      "CHOCOLATE",
      "WHITE ROMAN",
      "WHITE",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI&IX" DIAMOND',
      'PINK "VI&IX" DIAMOND',
      "CHOCOLATE JUBILEE DIAMOND",
      "SILVER FLUTED",
      "SILVER FLUTED DIAMOND",
      "SILVER PALM",
      "SILVER PALM DIAMOND",
      "SLATE FLUTED DIAMOND",
    ],
  },
  {
    model: "126203",
    dials: [
      "WIMBLEDON",
      "CHAMPAGNE",
      "WHITE",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      'GREEN "VI&IX" DIAMOND',
      'SILVER "VI&IX" DIAMOND',
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE FLUTED",
      "CHAMPAGNE FLUTED DIAMOND",
      "CHAMPAGNE PALM",
      "CHAMPAGNE PALM DIAMOND",
      "SILVER JUBILEE DIAMOND",
    ],
  },
  {
    model: "126231",
    dials: [
      "SLATE",
      "WIMBLEDON",
      "CHOCOLATE",
      "WHITE ROMAN",
      "WHITE",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI&IX" DIAMOND',
      'PINK "VI&IX" DIAMOND',
      "CHOCOLATE JUBILEE DIAMOND",
      "SILVER FLUTED",
      "SILVER FLUTED DIAMOND",
      "SILVER PALM",
      "SILVER PALM DIAMOND",
      "SLATE FLUTED DIAMOND",
    ],
  },
  {
    model: "126233",
    dials: [
      "WIMBLEDON",
      "CHAMPAGNE",
      "WHITE",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      'GREEN "VI&IX" DIAMOND',
      'SILVER "VI&IX" DIAMOND',
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE FLUTED",
      "CHAMPAGNE FLUTED DIAMOND",
      "CHAMPAGNE PALM",
      "CHAMPAGNE PALM DIAMOND",
      "SILVER JUBILEE DIAMOND",
    ],
  },
  {
    model: "126234",
    dials: [
      "BLACK",
      "WIMBLEDON",
      "BLUE",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "BLUE DIAMOND",
      "WHITE MOP DIAMOND",
      'PINK "VI&IX" DIAMOND',
      'PURPLE "VI&IX" DIAMOND',
      'SILVER "VI&IX" DIAMOND',
      "BLUE FLUTED",
      "BLUE FLUTED DIAMOND",
      "BLUE JUBILEE DIAMOND",
      "GREEN PALM",
      "GREEN PALM DIAMOND",
      "PINK JUBILEE DIAMOND",
    ],
  },
  {
    model: "126300",
    dials: [
      "BLACK",
      "SLATE",
      "WIMBLEDON",
      "BLUE",
      "BLUE ROMAN",
      "GREEN",
      "SILVER",
      "WHITE",
      "WHITE ROMAN",
      "BLUE FLUTED",
      "GREEN FLUTED",
    ],
  },
  {
    model: "126301",
    dials: [
      "WIMBELDON",
      "CHOCOLATE",
      "SUNDUST",
      "CHOCOLATE DIAMOND",
      "SUNDUST DIAMOND",
      "SLATE FLUTED",
      "SILVER FLUTED",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "126303",
    dials: [
      "BLACK",
      "WIMBLEDON",
      "CHAMPAGNE",
      "SILVER",
      "WHITE",
      "BLACK DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE FLUTED",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "126331",
    dials: [
      "WIMBLEDON",
      "CHOCOLATE",
      "SUNDUST",
      "CHOCOLATE DIAMOND",
      "SUNDUST DIAMOND",
      "SLATE FLUTED",
      "SILVER FLUTED",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "126333",
    dials: [
      "BLACK",
      "WIMBLEDON",
      "CHAMPAGNE",
      "SILVER",
      "WHITE",
      "BLACK DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE FLUTED",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "126334",
    dials: [
      "BLACK",
      "SLATE",
      "WIMBLEDON",
      "BLUE",
      "BLUE ROMAN",
      "MINT GREEN",
      "SILVER",
      "WHITE",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "SLATE DIAMOND",
      "BLUE DIAMOND",
      "BLUE FLUTED",
      "GREEN FLUTED",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "126503",
    dials: ["BLACK", "CHAMPAGNE", "WHITE", "BLACK DIAMOND"],
  },
  {
    model: "126505",
    dials: ["BLACK", "SUNDUST", "BLACK DIAMOND"],
  },
  {
    model: "126506",
    dials: ["ICE BLUE", "ICE BLUE DIAMOND"],
  },
  {
    model: "126508",
    dials: [
      "BLACK",
      "CHAMPAGNE",
      "WHITE",
      "BLACK DIAMOND",
      "BLACK/CHAMPAGNE",
      "CHAMPAGNE/BLACK",
    ],
  },
  {
    model: "126509",
    dials: [
      "BLACK",
      "STEEL",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "WHITE MOP DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "126600",
    dials: ["BLACK"],
  },
  {
    model: "126603",
    dials: ["BLACK"],
  },
  {
    model: "126621",
    dials: ["CHOCOLATE", "BLACK"],
  },
  {
    model: "126622",
    dials: ["BLUE", "SLATE"],
  },
  {
    model: "126655",
    dials: ["BLACK", "PAVE DIAMOND"],
  },
  {
    model: "126900",
    dials: ["BLACK"],
  },
  {
    model: "128235",
    dials: [
      "WHITE ROMAN",
      "BROWN OMBRE",
      "SLATE",
      "PINK DIAMOND",
      "WHITE MOP DIAMOND",
      "EISENKIESEL  VI&IX",
      "TURQUOISE  DIAMOND ROMAN",
      "GREEN AVENTURINE  VI&IX",
      "PAVE 10 BAGUETTE-CUT SAPPHIRES IN RAINBOW COLOURS",
      "SILVER DIAMOND",
      "BLUE-GREEN DIAMOND",
      "BROWN OMBRE DIAMOND",
    ],
  },
  {
    model: "128236",
    dials: [
      "SILVER",
      "WHITE ROMAN",
      "BLUE OMBRE",
      "WHITE MOP DIAMOND",
      "TURQUOISE  VI&IX",
      "PINK OPAL 32° VI&IX 24°",
      "PAVE 10 BAGUETTE-CUT SAPPHIRES IN RAINBOW COLOURS",
      "BLUE DIAMOND",
      "PINK DIAMOND",
      "BLUE OMBRE DIAMOND",
      "ICE BLUE ROMAN",
      "ICE BLUE 10 BAGUETTE-CUT DIAMOND",
    ],
  },
  {
    model: "128238",
    dials: [
      "CHAMPAGNE",
      "WHITE",
      "WHITE ROMAN",
      "GREEN DIAMOND",
      "DARK GREY DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      "TURQUOISE  VI&IX",
      "CARNELIAN  VI&IX",
      "DIAMOND-PAVE IN RAINBOW COLOURS",
      "GREEN OMBRE",
    ],
  },
  {
    model: "128239",
    dials: [
      "SILVER",
      "WHITE ROMAN",
      "BLUE OMBRE",
      "WHITE MOP DIAMOND",
      "TURQUOISE  VI&IX",
      "PINK OPAL 32° VI&IX 24°",
      "PAVE 10 BAGUETTE-CUT SAPPHIRES IN RAINBOW COLOURS",
      "BLUE DIAMOND",
      "PINK DIAMOND",
      "BLUE OMBRE DIAMOND",
    ],
  },
  {
    model: "136660",
    dials: ["BLACK", "D-BLUE"],
  },
  {
    model: "168622",
    dials: ["PLATINUM"],
  },
  {
    model: "168623",
    dials: ["CHAMPAGNE", "WHITE", "STEEL", "BLUE", "BLACK MOP"],
  },
  {
    model: "176200",
    dials: ["BLACK", "GREEN", "PINK", "RED GRAPE", "SILVER", "WHITE"],
  },
  {
    model: "177200",
    dials: [
      "BLACK",
      "BLUE ROMAN",
      "DARK GREY ROMAN",
      "RED GRAPE ROMAN",
      "SILVER",
      "WHITE ROMAN",
    ],
  },
  {
    model: "178158",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178159",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "178240",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
    ],
  },
  {
    model: "178241",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "PINK",
      "PINK ROMAN",
      "PINK FLORAL MOTIF ARABIC 6",
      "PURPLE ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "178243",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178245",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "PINK",
      "PINK ROMAN",
      "PINK FLORAL MOTIF ARABIC 6",
      "PURPLE ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "178248",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178271",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "PINK",
      "PINK ROMAN",
      "PINK FLORAL MOTIF ARABIC 6",
      "PURPLE ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "178273",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178274",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "178275",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "PINK",
      "PINK ROMAN",
      "PINK FLORAL MOTIF ARABIC 6",
      "PURPLE ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "178278",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178279",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "178288",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178313",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178341",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "PINK",
      "PINK ROMAN",
      "PINK FLORAL MOTIF ARABIC 6",
      "PURPLE ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "178343",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178344",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "178383",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE FLORAL MOTIF ARABIC 6",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "SILVER ROMAN VI  DIAMOND",
      "BLACK",
      "OLIVER GREEN ROMAN VI DIAMOND",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK MOP JUBILEE DIAMOND",
    ],
  },
  {
    model: "178384",
    dials: [
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "DARK RHODIUM FLORAL MOTIF ARABIC 6",
      "PINK",
      "PINK ROMAN",
      "BLUE",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "PINK MOP ROMAN",
      "PURPLE ROMAN VI DIAMOND",
      "BRONZE ROMAN VI DIAMOND",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "179136",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "179138",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179158",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179159",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "179160",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
    ],
  },
  {
    model: "179161",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "STEEL ROMAN",
      "PINK",
      "PINK ROMAN",
      "PINK ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE MOP LOTUS FLOWER MOTIF VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "METEORITE DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179163",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179171",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "STEEL ROMAN",
      "PINK",
      "PINK ROMAN",
      "PINK ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE MOP LOTUS FLOWER MOTIF VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "METEORITE DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179173",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179174",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "179175",
    dials: [
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE MOP ROMAN VI DIAMOND",
      "SILVER",
      "STEEL ROMAN",
      "PINK",
      "PINK ROMAN",
      "PINK ROMAN VI DIAMOND",
      "BLACK ROMAN",
      "BLACK MOP ROMAN",
      "CHOCOLATE ROMAN VI DIAMOND",
      "WHITE MOP LOTUS FLOWER MOTIF VI DIAMOND",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "METEORITE DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179178",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179179",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "179313",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179383",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179384",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "179458",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "SILVER",
      "STEEL ROMAN",
      "BLACK",
      "BLACK MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "YELLOW GOLD CRYSTALS DIAMOND",
      "WHITE DIAMOND",
      "IVORY DIAMOND",
      "WHITE MOP DIAMOND",
      "GOLD CRYSTALS JUBILEE DIAMOND",
      "SILVER DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "179459",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "BLACK",
      "BLACK ROMAN",
      "WHITE MOP ROMAN",
      "WHITE",
      "SILVER",
      "PINK MOP ROMAN",
      "PINK",
      "BLUE",
      "BLACK",
      "BLACK MOP ROMAN",
      "IVORY",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "214270",
    dials: ["BLACK"],
  },
  {
    model: "216570",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "218206",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "IVORY ROMAN CONCENTRIC",
      "SILVER DIAMOND",
      "RHODIUM ROMAN",
      "GREEN ENAMEL PAVE HOUR MARKERS",
      "CHOCOLATE ROMAN",
      "BLUE WAVES ARABICIC",
      "BLUE ENAMEL PAVE HOUR MARKERS",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BLACK DIAMOND",
      "BLACK ENAMEL PAVE HOUR MARKERS",
      "ICE BLUE ROMAN",
      "ICE BLUE ROMAN CONCENTRIC",
      "ICE BLUE ARABICIC",
      "ICE BLUE DIAMOND",
      "ICE BLUE ROMAN DIAMOND",
    ],
  },
  {
    model: "218235",
    dials: [
      "IVORY ROMAN",
      "PINK ROMAN",
      "PINK DIAMOND",
      "PINK ROMAN CONCENTRIC",
      "CHOCOLATE ROMAN",
      "BRONZE WAVES ARABICIC",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BLACK DIAMOND",
    ],
  },
  {
    model: "218238",
    dials: [
      "BLACK",
      "GREEN ROMAN",
      "GREEN OMBRE ROMAN",
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "SILVER ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ONYX DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "218239",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "IVORY ROMAN CONCENTRIC",
      "SILVER DIAMOND",
      "RHODIUM ROMAN",
      "GREEN ENAMEL PAVE HOUR MARKERS",
      "CHOCOLATE ROMAN",
      "BLUE WAVES ARABICIC",
      "BLUE ENAMEL PAVE HOUR MARKERS",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BLACK DIAMOND",
      "BLACK ENAMEL PAVE HOUR MARKERS",
    ],
  },
  {
    model: "218348",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE 8 BAGUETTE DIAMOND 2 BAGUETTE RUBIES",
      "WHITE ROMAN",
      "IVORY ARABICIC CONCENTRIC",
      "SILVER ROMAN",
      "BLACK WAVES ARABICIC",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
    ],
  },
  {
    model: "218349",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "IVORY ROMAN CONCENTRIC",
      "SILVER DIAMOND",
      "RHODIUM ROMAN",
      "GREEN ENAMEL PAVE HOUR MARKERS",
      "CHOCOLATE ROMAN",
      "BLUE WAVES ARABICIC",
      "BLUE ENAMEL PAVE HOUR MARKERS",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BLACK DIAMOND",
      "BLACK ENAMEL PAVE HOUR MARKERS",
    ],
  },
  {
    model: "218398",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE 8 BAGUETTE DIAMOND 2 BAGUETTE RUBIES",
      "WHITE ROMAN",
      "IVORY ARABICIC CONCENTRIC",
      "SILVER ROMAN",
      "BLACK WAVES ARABICIC",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
    ],
  },
  {
    model: "218399",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "IVORY ROMAN CONCENTRIC",
      "SILVER DIAMOND",
      "RHODIUM ROMAN",
      "GREEN ENAMEL PAVE HOUR MARKERS",
      "CHOCOLATE ROMAN",
      "BLUE WAVES ARABICIC",
      "BLUE ENAMEL PAVE HOUR MARKERS",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "BLACK DIAMOND",
      "BLACK ENAMEL PAVE HOUR MARKERS",
    ],
  },
  {
    model: "224270",
    dials: ["BLACK"],
  },
  {
    model: "226570",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "226627",
    dials: ["BLACK"],
  },
  {
    model: "226658",
    dials: ["BLACK"],
  },
  {
    model: "226659",
    dials: ["BLACK", "FALCON EYE"],
  },
  {
    model: "228235",
    dials: [
      "BLACK ROMAN",
      "CHOCOLATE ROMAN",
      "CHOCOLATE",
      "OLIVE GREEN ROMAN",
      "SUNDUST ROMAN",
      "WHITE ROMAN",
      "EISENKIESEL DIAMOND",
      "CHOCOLATE DIAMOND",
      "SUNDUST DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
      "SUNDSUT STRIPE",
    ],
  },
  {
    model: "228236",
    dials: [
      "BLACK",
      "SLATE",
      "BLUE ROMAN",
      "BLUE OMBRE ROMAN",
      "ICE BLUE ROMAN",
      "ICE BLUE",
      "OLIVE GREEN ROMAN",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ICE BLUE DIAMOND",
      "SILVER DIAMOND",
      "METEORITE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "228238",
    dials: [
      "BLACK",
      "GREEN ROMAN",
      "GREEN OMBRE ROMAN",
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "SILVER ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ONYX DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "228239",
    dials: [
      "BLACK",
      "SLATE",
      "BLUE ROMAN",
      "BLUE OMBRE ROMAN",
      "OLIVE GREEN ROMAN",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "SILVER DIAMOND",
      "METEORITE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "268621",
    dials: ["CHOCOLATE", "BLACK"],
  },
  {
    model: "268622",
    dials: ["SLATE", "BLUE"],
  },
  {
    model: "268655",
    dials: ["BLACK", "PAVE DIAMOND"],
  },
  {
    model: "276200",
    dials: ["BLACK", "BLUE", "PINK", "SILVER"],
  },
  {
    model: "277200",
    dials: [
      "BLACK",
      "BLUE",
      "PINK",
      "SILVER",
      "GREEN",
      "TURQUOISE",
      "CELEBRATION",
      "CANDY PINK",
      "CORAL RED",
      "YELLOW",
    ],
  },
  {
    model: "278240",
    dials: [
      "BLACK ROMAN",
      "DARK GREY",
      "DARK GREY ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
    ],
  },
  {
    model: "278241",
    dials: [
      "SLATE",
      "PINK ROMAN",
      "PINK",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI" DIAMOND',
      'CHOCOLATE "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "SILVER FLORAL DIAMOND",
    ],
  },
  {
    model: "278243",
    dials: [
      "CHAMPAGNE",
      "WHITE ROMAN",
      "BLACK MOP DIAMOND",
      "DARK GREY DIAMOND",
      "OLIVE GREEN DIAMOND",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARY GREY "VI" DIAMOND',
      'OLIVE GREEN "VI" DIAMOND',
      'SILVER "VI" DIAMOND',
      "OLIVE GREEN FLORAL DIAMOND",
    ],
  },
  {
    model: "278271",
    dials: [
      "SLATE",
      "PINK ROMAN",
      "PINK",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI" DIAMOND',
      'CHOCOLATE "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "SILVER FLORAL DIAMOND",
    ],
  },
  {
    model: "278273",
    dials: [
      "CHAMPAGNE",
      "WHITE ROMAN",
      "BLACK MOP DIAMOND",
      "DARK GREY DIAMOND",
      "OLIVE GREEN DIAMOND",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARY GREY "VI" DIAMOND',
      'OLIVE GREEN "VI" DIAMOND',
      'SILVER "VI" DIAMOND',
      "OLIVE GREEN FLORAL DIAMOND",
    ],
  },
  {
    model: "278274",
    dials: [
      "BLACK ROMAN",
      "DARK GREY",
      "DARK GREY ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'PINK "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "BLUE FLORAL DIAMOND",
    ],
  },
  {
    model: "278275",
    dials: [
      "SLATE",
      "PINK ROMAN",
      "PINK",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI" DIAMOND',
      'CHOCOLATE "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "SILVER FLORAL DIAMOND",
    ],
  },
  {
    model: "278278",
    dials: [
      "CHAMPAGNE",
      "WHITE ROMAN",
      "BLACK MOP DIAMOND",
      "DARK GREY DIAMOND",
      "OLIVE GREEN DIAMOND",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARY GREY "VI" DIAMOND',
      'OLIVE GREEN "VI" DIAMOND',
      'SILVER "VI" DIAMOND',
      "OLIVE GREEN FLORAL DIAMOND",
    ],
  },
  {
    model: "279161",
    dials: [
      "CHOCOLATE ROMAN",
      "CHOCOLATE",
      "PINK",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PURPLE DIAMOND",
      "OLIVE GREEN DIAMOND",
      "WHITE MOP DIAMOND",
      "CHOCOLATE STAR DIAMOND",
      "PINK STAR DIAMOND",
    ],
  },
  {
    model: "279163",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "SILVER ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      "CHAMPAGNE STAR DIMAMOND",
      "SILVER STAR DIAMOND",
    ],
  },
  {
    model: "279171",
    dials: [
      "CHOCOLATE ROMAN",
      "CHOCOLATE",
      "PINK",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PURPLE DIAMOND",
      "OLIVE GREEN DIAMOND",
      "WHITE MOP DIAMOND",
      "CHOCOLATE STAR DIAMOND",
      "PINK STAR DIAMOND",
    ],
  },
  {
    model: "279173",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "SILVER ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      "CHAMPAGNE STAR DIMAMOND",
      "SILVER STAR DIAMOND",
    ],
  },
  {
    model: "279175",
    dials: [
      "CHOCOLATE",
      "CHOCOLATE ROMAN",
      "PINK",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PURPLE DIAMOND",
      "OLIVE GREEN DIAMOND",
      "WHITE MOP DIAMOND",
      "CHOCOLATE STAR DIAMOND",
      "PINK STAR DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "279178",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "SILVER",
      "SILVER ROMAN",
      "WHITE ROMAN",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      "CHAMPAGNE STAR DIMAMOND",
      "SILVER STAR DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "326135",
    dials: ["CHOCOLATE ARABIC", "SUNDUST ROMAN", "SLATE", "WHITE"],
  },
  {
    model: "326933",
    dials: ["BLACK", "CHAMPAGNE", "WHITE"],
  },
  {
    model: "326934",
    dials: ["BLACK", "BLUE", "WHITE"],
  },
  {
    model: "326938",
    dials: ["CHAMPAGNE ARABIC", "CHAMPAGNE", "BLACK", "WHITE"],
  },
  {
    model: "326939",
    dials: ["IVORY ROMAN"],
  },
  {
    model: "336235",
    dials: ["SLATE", "CHOCOLATE", "WHITE"],
  },
  {
    model: "336238",
    dials: ["BLACK", "WHITE", "CHAMPAGNE"],
  },
  {
    model: "336239",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "336933",
    dials: ["BLACK", "WHITE", "CHAMPAGNE"],
  },
  {
    model: "336934",
    dials: ["BLACK", "WHITE", "BLUE", "MINT GREEN"],
  },
  {
    model: "336935",
    dials: ["SLATE", "CHOCOLATE", "WHITE", "BLUE"],
  },
  {
    model: "336938",
    dials: ["BLACK", "WHITE", "CHAMPAGNE"],
  },
  {
    model: "116185BBR",
    dials: [
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "STEEL ROMAN",
      "STEEL DIAMOND",
      "PINK",
      "PINK ROMAN",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "CHOCOLATE FLORAL MOTIF ARABICIC 6-9 DIAMOND",
      "BLACK DIAMOND",
      "BLACK JUBILEE DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "116285BBR",
    dials: [
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "STEEL ROMAN",
      "STEEL DIAMOND",
      "PINK",
      "PINK ROMAN",
      "PINK DIAMOND",
      "PINK JUBILEE DIAMOND",
      "BLACK",
      "BLACK ROMAN",
      "BLACK ARABICIC CONCENTRIC",
      "CHOCOLATE FLORAL MOTIF ARABICIC 6-9 DIAMOND",
      "BLACK DIAMOND",
      "BLACK JUBILEE DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "116400GV",
    dials: ["BLACK", "BLUE"],
  },
  {
    model: "116500LN",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "116515LN",
    dials: [
      "BLACK",
      "BLACK DIAMOND",
      "CHOCOLATE",
      "CHOCOLATE ARABICIC",
      "IVORY",
      "SUNDUST",
      "SUNDUST DIAMOND",
    ],
  },
  {
    model: "116518LN",
    dials: [
      "BLACK",
      "BLACK DIAMOND",
      "BLACK/CHAMPAGNE",
      "CHAMPAGNE",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE/BLACK",
      "METEORITE",
      "WHITE",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "116589RBR",
    dials: [
      "METEORITE ROMAN",
      "BLACK ENAMEL PAVE ARABICIC",
      "PINK MOP DIAMOND",
      "SLATE ARABICIC",
      "BLUE ENAMEL PAVE ROMAN",
      "BLACK DIAMOND",
      "GOLD CRYSTAL DIAMOND",
      "BLACK ENAMEL PAVE ROMAN",
    ],
  },
  {
    model: "116599RBR",
    dials: [
      "METEORITE ROMAN",
      "BLACK ENAMEL PAVE ARABICIC",
      "PINK MOP DIAMOND",
      "SLATE ARABICIC",
      "BLUE ENAMEL PAVE ROMAN",
      "BLACK DIAMOND",
      "GOLD CRYSTAL DIAMOND",
      "BLACK ENAMEL PAVE ROMAN",
    ],
  },
  {
    model: "116610LN",
    dials: ["BLACK"],
  },
  {
    model: "116610LV",
    dials: ["HULK"],
  },
  {
    model: "116613LN",
    dials: ["BLACK"],
  },
  {
    model: "116613LB",
    dials: ["BLUE"],
  },
  {
    model: "116618LN",
    dials: ["BLACK"],
  },
  {
    model: "116618LB",
    dials: ["BLUE"],
  },
  {
    model: "116619LB",
    dials: ["SMURF"],
  },
  {
    model: "116710BLNR",
    dials: ["BATMAN"],
  },
  {
    model: "116710LN",
    dials: ["BLACK"],
  },
  {
    model: "116713LN",
    dials: ["BLACK"],
  },
  {
    model: "116718LN",
    dials: ["BLACK", "GREEN"],
  },
  {
    model: "116759SA",
    dials: ["BLACK", "PAVE"],
  },
  {
    model: "116759SANR",
    dials: ["BLACK", "PAVE"],
  },
  {
    model: "116759SARU",
    dials: ["BLACK", "PAVE"],
  },
  {
    model: "126281RBR",
    dials: [
      "SLATE",
      "WIMBLEDON",
      "CHOCOLATE",
      "WHITE ROMAN",
      "WHITE",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI&IX" DIAMOND',
      'PINK "VI&IX" DIAMOND',
      "SILVER FLUTED",
      "SILVER FLUTED DIAMOND",
      "SILVER PALM",
      "SILVER PLAM DIAMOND",
      "SLATE FLUTED DIAMOND",
    ],
  },
  {
    model: "126283RBR",
    dials: [
      "WIMBLEDON",
      "CHAMPAGNE",
      "WHITE",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      'OLIVE GREEN "VI&IX" DIAMOND',
      'SILVER "VI&IX" DIAMOND',
    ],
  },
  {
    model: "126284RBR",
    dials: [
      "BLACK",
      "WIMBLEDON",
      "BLUE",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "BLUE DIAMOND",
      "WHITE MOP DIAMOND",
      'PINK "VI&IX" DIAMOND',
      'PURPLE "VI&IX" DIAMOND',
      'SLATE "VI&IX" DIAMOND',
    ],
  },
  {
    model: "126500LN",
    dials: ["BLACK", "WHITE"],
  },
  {
    model: "126515LN",
    dials: ["BLACK", "SUNDUST", "BLACK DIAMOND"],
  },
  {
    model: "126518LN",
    dials: [
      "BLACK",
      "CHAMPAGNE",
      "WHITE",
      "BLACK DIAMOND",
      "BLACK/CHAMPAGNE",
      "CHAMPAGNE/BLACK",
    ],
  },
  {
    model: "126519LN",
    dials: ["BLACK", "STEEL", "BLACK DIAMOND"],
  },
  {
    model: "126610LN",
    dials: ["BLACK"],
  },
  {
    model: "126610LV",
    dials: ["STARBUCK"],
  },
  {
    model: "126613LB",
    dials: ["BLUE"],
  },
  {
    model: "126613LN",
    dials: ["BLACK"],
  },
  {
    model: "126618LB",
    dials: ["BLUE"],
  },
  {
    model: "126618LN",
    dials: ["BLACK"],
  },
  {
    model: "126619LB",
    dials: ["BLACK"],
  },
  {
    model: "126710BLNR",
    dials: ["BATMAN"],
  },
  {
    model: "126710BLRO",
    dials: ["PEPSI"],
  },
  {
    model: "126710GRNR",
    dials: ["BRUCE WAYNE"],
  },
  {
    model: "126711CHNR",
    dials: ["ROOT BEER"],
  },
  {
    model: "126713GRNR",
    dials: ["BLACK"],
  },
  {
    model: "126715CHNR",
    dials: ["ROOT BEER"],
  },
  {
    model: "126718GRNR",
    dials: ["BLACK"],
  },
  {
    model: "126719BLRO",
    dials: ["BLUE", "METEORITE"],
  },
  {
    model: "126720VTNR",
    dials: ["SPRITE"],
  },
  {
    model: "128345RBR",
    dials: [
      "WHITE ROMAN",
      "BROWN OMBRE",
      "SLATE",
      "PINK DIAMOND",
      "WHITE MOP DIAMOND",
      "EISENKIESEL  VI&IX",
      "TURQUOISE  VI&IX",
      "GREEN AVENTURINE  VI&IX",
      "PAVE 10 BAGUETTE-CUT SAPPHIRES IN RAINBOW COLOURS",
      "SILVER DIAMOND",
      "BLUE-GREEN DIAMOND",
      "SLATE DIAMOND",
      "BROWN OMBRE DIAMOND",
    ],
  },
  {
    model: "128348RBR",
    dials: [
      "CHAMPAGNE",
      "WHITE",
      "WHITE ROMAN",
      "GREEN DIAMOND",
      "DARK GREY DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      "TURQUOISE  VI&IX",
      "CARNELIAN  VI&IX",
      "DIAMOND-PAVE IN RAINBOW COLOURS",
      "GREEN OMBRE",
    ],
  },
  {
    model: "128349RBR",
    dials: [
      "SILVER",
      "WHITE ROMAN",
      "BLUE OMBRE",
      "WHITE MOP DIAMOND",
      "TURQUOISE  VI&IX",
      "PINK OPAL 32° VI&IX 24°",
      "PAVE 10 BAGUETTE-CUT SAPPHIRES IN RAINBOW COLOURS",
      "BLUE DIAMOND",
      "PINK DIAMOND",
      "BLUE OMBRE DIAMOND",
    ],
  },
  {
    model: "128396TBR",
    dials: [
      "SILVER",
      "WHITE ROMAN",
      "BLUE OMBRE",
      "WHITE MOP DIAMOND",
      "TURQUOISE  VI&IX",
      "PINK OPAL 32° VI&IX 24°",
      "PAVE 10 BAGUETTE-CUT SAPPHIRES IN RAINBOW COLOURS",
      "BLUE DIAMOND",
      "PINK DIAMOND",
      "BLUE OMBRE DIAMOND",
      "ICE BLUE ROMAN",
      "ICE BLUE 10 BAGUETTE-CUT DIAMOND",
    ],
  },
  {
    model: "18956BRIL",
    dials: [
      "WHITE ROMAN",
      "SILVER",
      "RHODIUM ROMAN",
      "SILVER DIAMOND",
      "SILVER JUBILEE DIAMOND",
      "RHODIUM 8 DIAMOND 2 EMERALD",
      "BLUE",
      "CHERRY",
      "BLACK",
      "BLACK DIAMOND",
      "WHITE MOP DIAMOND",
      "CAROUSEL OF WHITE MOP DIAMOND",
      "PLATINUM MOP WITH OXFORD MOTIF DIAMOND",
      "METEORITE 2BR",
      "LAPIS LAZULI DIAMOND",
      "BLUE ENAMEL PAVE ARABICIC",
      "BLACK MOP DIAMOND",
      "ICE BLUE",
    ],
  },
  {
    model: "18958BRIL",
    dials: [
      "CHAMPAGNE",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE DIAMOND",
      "CHAMPAGNE JUBILEE DIAMOND",
      "WHITE",
      "WHITE ROMAN",
      "SILVER",
      "SILVER DIAMOND",
      "GREEN",
      "BLACK",
      "COGNAC",
      "BLACK DIAMOND",
      "BLACK 8 DIAMOND 2 RUBIES",
      "CHAMPAGNE MOP JUBILEE DIAMOND",
      "CHAMPAGNE MYRIAD ROMAN",
      "WHITE MOP DIAMOND",
      "WHITE MOP ROMAN DIAMOND PAVE CENTER",
      "METEORITE DIAMOND",
    ],
  },
  {
    model: "228345RBR",
    dials: [
      "SLATE OMBRE ROMAN",
      "CHOCOLATE ROMAN",
      "CHOCOLATE",
      "OLIVE GREEN ROMAN",
      "SUNDUST ROMAN",
      "WHITE ROMAN",
      "EISENKIESEL DIAMOND",
      "CHOCOLATE  DIAMOND",
      "SUNDUST DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "228348RBR",
    dials: [
      "BLACK",
      "GREEN ROMAN",
      "GREEN OMBRE ROMAN",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE",
      "SILVER ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ONYX DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "228349RBR",
    dials: [
      "BLACK",
      "SLATE",
      "BLUE ROMAN",
      "BLUE OMBRE ROMAN",
      "OLIVE GREEN ROMAN",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "SILVER DIAMOND",
      "METEORITE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "228396TBR",
    dials: [
      "BLACK",
      "SLATE",
      "BLUE ROMAN",
      "BLUE OMBRE ROMAN",
      "ICE BLUE ROMAN",
      "ICE BLUE",
      "OLIVE GREEN ROMAN",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ICE BLUE DIAMOND",
      "SILVER DIAMOND",
      "METEORITE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "228398TBR",
    dials: [
      "BLACK",
      "GREEN ROMAN",
      "GREEN OMBRE ROMAN",
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE",
      "SILVER ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ONYX DIAMOND",
      "CHAMPAGNE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "278285RBR",
    dials: [
      "SLATE",
      "PINK",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI" DIAMOND',
      'CHOCOLATE "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "SILVER FLORAL DIAMOND",
    ],
  },
  {
    model: "278288RBR",
    dials: [
      "CHAMPAGNE",
      "WHITE ROMAN",
      "BLACK MOP DIAMOND",
      "DARK GREY DIAMOND",
      "OLIVE GREEN DIAMOND",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'OLIVE GREEN "VI" DIAMOND',
      'SILVER "VI" DIAMOND',
      "GREEN FLORAL DIAMOND",
    ],
  },
  {
    model: "278289RBR",
    dials: [
      "BLACK ROMAN",
      "DARK GREY",
      "DARK GREY ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'PINK "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "BLUE FLORAL DIAMOND",
    ],
  },
  {
    model: "278341RBR",
    dials: [
      "SLATE",
      "PINK",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI" DIAMOND',
      'CHOCOLATE "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "SILVER FLORAL DIAMOND",
    ],
  },
  {
    model: "278343RBR",
    dials: [
      "CHAMPAGNE",
      "WHITE ROMAN",
      "BLACK MOP DIAMOND",
      "DARK GREY DIAMOND",
      "OLIVE GREEN DIAMOND",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'OLIVE GREEN "VI" DIAMOND',
      'SILVER "VI" DIAMOND',
      "GREEN FLORAL DIAMOND",
    ],
  },
  {
    model: "278344RBR",
    dials: [
      "BLACK ROMAN",
      "DARK GREY",
      "DARK GREY ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'PINK "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "BLUE FLORAL DIAMOND",
    ],
  },
  {
    model: "278381RBR",
    dials: [
      "SLATE",
      "PINK",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'SLATE "VI" DIAMOND',
      'CHOCOLATE "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "SILVER FLORAL DIAMOND",
    ],
  },
  {
    model: "278383RBR",
    dials: [
      "CHAMPAGNE",
      "WHITE ROMAN",
      "BLACK MOP DIAMOND",
      "DARK GREY DIAMOND",
      "OLIVE GREEN DIAMOND",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'OLIVE GREEN "VI" DIAMOND',
      'SILVER "VI" DIAMOND',
      "GREEN FLORAL DIAMOND",
    ],
  },
  {
    model: "278384RBR",
    dials: [
      "BLACK ROMAN",
      "DARK GREY",
      "DARK GREY ROMAN",
      "PINK",
      "PINK ROMAN",
      "BLUE ROMAN",
      "MINT GREEN",
      "SILVER",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      'DARK GREY "VI" DIAMOND',
      'PINK "VI" DIAMOND',
      'PURPLE "VI" DIAMOND',
      "BLUE FLORAL DIAMOND",
    ],
  },
  {
    model: "279135RBR",
    dials: [
      "CHOCOLATE",
      "PINK",
      "CHOCOLATE ROMAN",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "OLIVE GREEN DIAMOND",
      "PURPLE DIAMOND",
      "WHITE MOP DIAMOND",
      "CHOCOLATE STAR DIAMOND",
      "PINK STAR DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "279138RBR",
    dials: [
      "CHAMPAGNE",
      "SILVER",
      "CHAMPAGNE ROMAN",
      "SILVER ROMAN",
      "WHITE ROMAN",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      "CHAMPAGNE STAR DIAMOND",
      "SILVER STAR DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "279381RBR",
    dials: [
      "CHOCOLATE",
      "PINK",
      "CHOCOLATE ROMAN",
      "PINK ROMAN",
      "WHITE ROMAN",
      "CHOCOLATE DIAMOND",
      "OLIVE GREEN DIAMOND",
      "PURPLE DIAMOND",
      "WHITE MOP DIAMOND",
      "CHOCOLATE STAR DIAMOND",
      "PINK STAR DIAMOND",
    ],
  },
  {
    model: "279383RBR",
    dials: [
      "CHAMPAGNE",
      "SILVER",
      "CHAMPAGNE ROMAN",
      "SILVER ROMAN",
      "WHITE ROMAN",
      "CHAMPAGNE DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      "CHAMPAGNE STAR DIAMOND",
      "SILVER STAR DIAMOND",
    ],
  },
  {
    model: "279458RBR",
    dials: ["PAVE DIAMOND"],
  },
  {
    model: "228206",
    dials: [
      "BLACK",
      "SLATE",
      "BLUE ROMAN",
      "BLUE OMBRE ROMAN",
      "ICE BLUE ROMAN",
      "ICE BLUE",
      "OLIVE GREEN ROMAN",
      "WHITE ROMAN",
      "BLACK DIAMOND",
      "ICE BLUE DIMAOND",
      "SILVER DIAMOND",
      "METEORITE DIAMOND",
      "WHITE MOP DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "326138",
    dials: ["BLACK", "CHAMPAGNE", "WHITE", "CHAMPAGNE ARABIC"],
  },
  {
    model: "326935",
    dials: ["SLATE", "WHITE", "CHOCOLATE", "SUNDUST ROMAN"],
  },
  {
    model: "279165",
    dials: [
      "CHOCOLATE DIAMOND",
      "CHOCOLATE",
      "CHOCOLATE ROMAN",
      "CHOCOLATE STAR DIAMOND",
      "OLIVE GREEN DIAMOND",
      "PURPLE DIAMOND",
      "SUNDUST",
      "SUNDUST ROMAN",
      "SUNDUST STAR DIAMOND",
      "WHITE MOP DIAMOND",
      "WHITE ROMAN",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "279160",
    dials: [
      "DARK GREY",
      "PINK",
      "SILVER",
      "DARK GREY ROMAN",
      "PINK ROMAN",
      "SILVER ROMAN",
      "WHITE ROMAN",
    ],
  },
  {
    model: "279166",
    dials: [],
  },
  {
    model: "279174",
    dials: [
      "DARK GREY",
      "PINK",
      "SILVER",
      "DARK GREY ROMAN",
      "PINK ROMAN",
      "SILVER ROMAN",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND IX",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "279163RBR",
    dials: [],
  },
  {
    model: "279384RBR",
    dials: [
      "DARK GREY",
      "PINK",
      "SILVER",
      "DARK GREY ROMAN",
      "PINK ROMAN",
      "SILVER ROMAN",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "SILVER DIAMOND IX",
      "WHITE MOP DIAMOND",
    ],
  },
  {
    model: "326238",
    dials: ["BLACK", "CHAMPAGNE", "WHITE"],
  },
  {
    model: "326235",
    dials: ["SLATE", "WHITE", "CHOCOLATE"],
  },
  {
    model: "279459RBR",
    dials: ["PAVE BLACK ROMAN"],
  },
  {
    model: "81409RBR",
    dials: ["PAVE ROMAN"],
  },
  {
    model: "81405RBR",
    dials: ["PAVE ROMAN"],
  },
  {
    model: "86409RBR",
    dials: ["PAVE ROMAN"],
  },
  {
    model: "86405RBR",
    dials: ["PAVE ROMAN"],
  },
  {
    model: "126660",
    dials: ["BLACK", "D-BLUE"],
  },
  {
    model: "50535",
    dials: ["WHITE"],
  },
  {
    model: "136668LB",
    dials: ["BLUE"],
  },
  {
    model: "326139",
    dials: ["BLACK ARABIC", "IVORY ROMAN"],
  },
  {
    model: "52506",
    dials: ["ICE BLUE"],
  },
  {
    model: "126539TBR",
    dials: [
      "STEEL DIAMOND",
      "WHITE MOP DIAMOND",
      "BLACK MOP DIAMOND",
      "BLACK DIAMOND",
      "STEEL",
      "BLACK",
    ],
  },
  {
    model: "128398TBR",
    dials: [
      "CARNELIAN DIAMOND",
      "PAVE DIAMOND",
      "TURQUOISE DIAMOND",
      "WHITE MOP DIAMOND",
      "CHAMPAGNE DIAMOND",
      "GREEN DIAMOND",
      "DARK GREY DIAMOND",
      "WHITE ROMAN",
      "WHITE",
      "CHAMPAGNE",
      "GREEN ROMAN",
    ],
  },
  {
    model: "128395TBR",
    dials: [
      "BROWN ROMAN",
      "WHITE ROMAN",
      "SLATE DIAMOND",
      "CHOCOLATE DIAMOND",
      "PINK DIAMOND",
      "BLUE-GREEN DIAMOND",
      "SILVER DIAMOND",
      "WHITE MOP DIAMOND",
      "EISENKIESEL DIAMOND",
      "TURQUOISE DIAMOND",
      "GREEN ROMAN DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "126535TBR",
    dials: ["SUNDUST DIAMOND", "BLACK DIAMOND", "SUNDUST", "BLACK"],
  },
  {
    model: "126579RBR",
    dials: [
      "BLACK",
      "STEEL",
      "BLACK DIAMOND",
      "BLACK MOP DIAMOND",
      "WHITE MOP DIAMOND",
      "STEEL DIAMOND",
    ],
  },
  {
    model: "126598TBR",
    dials: [
      "CHAMPAGNE DIAMOND",
      "BLACK DIAMOND",
      "WHITE",
      "CHAMPAGNE",
      "BLACK",
    ],
  },
  {
    model: "128399TBR",
    dials: [
      "BLUE ROMAN",
      "SILVER",
      "WHITE ROMAN",
      "PINK DIAMOND",
      "BLUE DIAMOND",
      "WHITE MOP DIAMOND",
      "PINK DIAMOND",
      "TURQUOISE DIAMOND",
      "PAVE DIAMOND",
    ],
  },
  {
    model: "126595TBR",
    dials: ["SUNDUST DIAMOND", "BLACK DIAMOND", "SUNDUST", "BLACK"],
  },
  {
    model: "6621/8",
    dials: [
      "CHAMPAGNE ARABIC",
      "CHAMPAGNE JUBILEE",
      "CHAMPAGNE DIAMOND",
      "WHITE ARABIC",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE DIAMOND",
      "BLUE ARABIC",
      "BLUE ROMAN",
      "SLATE JUBILEE",
      "BLACK MOP DIAMOND",
      "BLACK MOP ROMAN",
    ],
  },
  {
    model: "6623/8",
    dials: [
      "CHAMPAGNE ARABIC",
      "CHAMPAGNE JUBILEE",
      "CHAMPAGNE DIAMOND",
      "WHITE ARABIC",
      "WHITE ROMAN",
      "WHITE MOP ROMAN",
      "WHITE DIAMOND",
      "BLUE ARABIC",
      "BLUE ROMAN",
      "SLATE JUBILEE",
    ],
  },
  {
    model: "5241/6",
    dials: ["ICE BLUE", "BLACK"],
  },
  {
    model: "6673/9",
    dials: [
      "WHITE ARABIC",
      "WHITE ROMAN",
      "SILVER JUBILEE DIAMOND",
      "PINK ROMAN",
      "BLUE ARABIC",
      "BLUE ROMAN",
      "BLUE DIAMOND",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "6683/9",
    dials: [
      "WHITE ARABIC",
      "WHITE ROMAN",
      "SILVER JUBILEE DIAMOND",
      "PINK ROMAN",
      "BLUE ARABIC",
      "BLUE ROMAN",
      "BLUE DIAMOND",
      "BLACK MOP DIAMOND",
      "WHITE ROMAN",
      "PINK ROMAN",
      "BLUE ROMAN",
    ],
  },
  {
    model: "6691/9",
    dials: ["WHITE ROMAN", "PINK ROMAN", "BLUE ROMAN"],
  },
  {
    model: "3612/8",
    dials: ["CHAMPAGNE ROMAN", "SILVER ROMAN"],
  },
  {
    model: "3761/8",
    dials: ["CHAMPAGNE ARABIC", "WHITE ROMAN", "SILVER ARABIC"],
  },
  {
    model: "5115/8",
    dials: [
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE ROMAN 3-6-9",
      "WHITE",
      "WHITE MOP ARABIC",
      "IVORY JUBILEE ROMAN",
      "SLATE ROMAN",
      "BLACK",
    ],
  },
  {
    model: "6110/8",
    dials: [
      "CHAMPAGNE ROMAN",
      "CHAMPAGNE ROMAN 3-6-9",
      "WHITE",
      "WHITE MOP ARABIC",
      "IVORY JUBILEE ROMAN",
      "SLATE ROMAN",
      "BLACK",
    ],
  },
  {
    model: "5115/9",
    dials: [
      "WHITE MOP ARABIC",
      "SILVER ROMAN 3-6-9",
      "SILVER ROMAN",
      "IVORY JUBILEE ROMAN",
      "SLATE ROMAN",
      "BROWN",
      "BLACK",
    ],
  },
  {
    model: "6110/9",
    dials: [
      "WHITE MOP ARABIC",
      "SILVER ROMAN 3-6-9",
      "SILVER ROMAN",
      "IVORY JUBILEE ROMAN",
      "SLATE ROMAN",
      "BROWN",
      "BLACK",
    ],
  },
  {
    model: "4233/8",
    dials: ["WHITE ARABIC", "BLACK ARABIC"],
  },
  {
    model: "4233/9",
    dials: ["WHITE ARABIC", "BLACK ARABIC"],
  },
  {
    model: "4243/8",
    dials: ["CHAMPAGNE", "WHITE", "BLACK ARABIC", "BLACK"],
  },
  {
    model: "4243/9",
    dials: ["WHITE", "SILVER", "BLACK ARABIC", "BLACK"],
  },
  {
    model: "5330/8",
    dials: [
      "WHITE ARABIC",
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP ROMAN",
      "CHAMPAGNE DIAMOND",
    ],
  },
  {
    model: "6311/8",
    dials: [
      "WHITE ROMAN",
      "WHITE DIAMOND",
      "WHITE MOP ROMAN",
      "CHAMPAGNE DIAMOND",
      "BLACK MOP ROMAN",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "6321/8",
    dials: ["BLACK MOP ROMAN", "BLACK MOP DIAMOND"],
  },
  {
    model: "5330/5",
    dials: ["SLATE ARABIC", "WHITE ARABIC"],
  },
  {
    model: "5330/9",
    dials: [
      "WHITE ROMAN",
      "WHITE ARABIC",
      "SLATE ARABIC",
      "BLACK MOP ROMAN",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "6311/9",
    dials: [
      "WHITE MOP ROMAN",
      "WHITE MOP DIAMOND",
      "PINK MOP ROMAN",
      "PINK DIAMOND",
      "BLACK MOP ROMAN",
      "BLACK MOP DIAMOND",
    ],
  },
  {
    model: "279139RBR",
    dials: [
      "DARK GREY",
      "PINK",
      "SILVER",
      "DARK GREY ROMAN",
      "PINK ROMAN",
      "SILVER ROMAN",
      "WHITE ROMAN",
      "DARK GREY DIAMOND",
      "PINK DIAMOND",
      "WHITE MOP DIAMOND",
      "SILVER DIAMOND IX",
      "PINK OPAL DIAMOND",
      "PAVE DIAMOND",
    ],
  },
];
