export const collectionDropdown = [
  "Blank",
  "Air-King",
  "Altiplano",
  "Aquanaut",
  "Aquatimer",
  "Assioma",
  "Avenger",
  "Arkade",
  "B.zero1",
  "Balancier Contemporain",
  "Ballon Bleu",
  "Bentley",
  "Big Bang",
  "Black Bay",
  "Black Shield",
  "Bvlgari Bvlgari",
  "Ballon Blanc",
  "Calatrava",
  "Calibre",
  "Cellini",
  "Chronomat",
  "ChronoPulse",
  "Classic",
  "Classic Fusion",
  // "Classic Racing",
  "Classique",
  "Cle",
  "Cockpit",
  "Code 11.59",
  "Complications",
  "Conquest",
  "Constellation",
  "Cosmograph Daytona",
  "Da Vinci",
  "Datejust",
  "Day-Date",
  "De Ville",
  "Diagono",
  "Différentiel d'Égalité",
  "DolceVita",
  "Double Tourbillon 30°",
  "Drive",
  "Drive de Cartier",
  "Easy Diver",
  "Endurer",
  "Equestrian",
  "Evidenza",
  "Excaliber",
  "Excalibur",
  "Explorer",
  "Explorer",
  "Explorer II",
  "Fastrider",
  "Fastrider Chronograph",
  "Flagship",
  "Galactic",
  "Geophysic",
  "GMT Earth",
  "GMT-Master",
  "GMT-Master II",
  "Golden Ellipse",
  "Gondolo",
  "Grand Complications",
  "Glamour Double Date",
  "Happy Sport",
  "Heritage",
  "Heritage Chrono",
  "High Jewellery",
  "Hommage",
  "HydroConquest",
  "Imperiale",
  "Ingenieur",
  "Jules Audemars",
  "L.U.C",
  "La Grande Classique",
  "La Marine",
  "La Monégasque",
  "Lange 1",
  "Le Brassus",
  "Leman",
  "Limelight",
  "Luminor",
  "Lvcea",
  "Master",
  "Master Collection",
  "Milgauss",
  "Millenary",
  "MP Collection",
  "Nautilus",
  "Navitimer",
  "Octo",
  "Overseas",
  "Oyster Perpetual",
  "Panthere",
  "Pearlmaster",
  "Pelagos",
  "Pilot's",
  "Polaris",
  "Polo",
  "Portofino",
  "Portofino",
  "Portugieser",
  "Portugieser",
  "Portuguese",
  "Possession",
  "Presence",
  "PrimaLuna",
  "Professional",
  "QP à Équation",
  "Radiomir",
  "Ranger",
  "Reine de Naples",
  "Rendez-Vous",
  "Rettangolo",
  "Reverso",
  "Ronde",
  "Roadster",
  "Rotonde De Cartier",
  "Royal Oak",
  "Royal Oak Concept",
  "Royal Oak Offshore",
  "Royal Oak Perpetual",
  "[Re]Master",
  "Santos",
  "Saxonia",
  "Sea-Dweller",
  "Seamaster",
  "Serpenti",
  "Signature 1",
  "Sky-Dweller",
  "Speedmaster",
  "Spirit of Big Bang",
  "Spirit Of Big Bang",
  "Square Bang",
  "Starliner",
  "Style",
  "Submariner",
  "Superocean",
  "Symphonette",
  "Tank",
  "Tradition",
  "Traditionnelle",
  "Transocean",
  "TUDOR Royal",
  "Twenty~4",
  "Type XX - XXI - XXII",
  "Tubogas",
  "Velvet",
  "Villeret",
  "Vintage",
  "World Time",
  "Yacht-Master",
  "Yacht-Master II",
  "Zeitwerk",
  "1926",
  "1815",
  "1908",
].sort((a, b) => a.localeCompare(b));

export const soldBoxDropdown = ["BLANK", "YES", "NO"];

export const boxInventoryStatusDropdown = ["All", "Available", "Sold"];

export const dialDropdown = [
  "Blank",
  "AUTAVIA",
  "AMMONITE",
  "BATMAN",
  "BLACK",
  "BLACK ARABIC",
  "BLACK ARABIC CONCENTRIC",
  "BLACK DIAMOND",
  "BLACK DIAMOND/RUBY",
  "BLACK DIAGONAL MOTIF",
  "BLACK JUBILEE ARABIC",
  "BLACK JUBILEE DIAMOND",
  "BLACK JUBILEE ROMAN",
  "BLACK MOP DIAMOND",
  "BLACK MOP ROMAN",
  "BLACK ROMAN",
  "BLACK ROMAN 9 STICK",
  "BLACK SUNBEAM ROMAN",
  "BLACK/BLUE",
  "BLACK/CHAMPAGNE",
  "BLUE",
  "BLUE ARABIC",
  "BLUE CONCENTRIC ARABIC",
  "BLUE DIAMOND",
  "BLUE FLUTED",
  "BLUE FLORAL",
  "BLUE JUBILEE DIAMOND",
  "BLUE ROMAN",
  "BLUE SODALITE DIAMOND",
  "BLUE WAVE ARABIC",
  "BRONZE FLOWER",
  "BRONZE VI DIAMOND",
  "BROWN",
  "BROWN FLOWER",
  "BROWN NIPPLE",
  "BLUE OMBRE ROMAN",
  "BROWN OMBRE ROMAN",
  "BLUE OMBRE 8+2 DIAMOND",
  "BLUE BAGUETTE DIAMOND",
  "BEIGE",
  "CELEBRATION",
  "CANDY PINK",
  "CARBON FIBER",
  "CHAMP SUNBEAM ROMAN",
  "CHAMP TAPESTRY",
  "CHAMP TUXEDO",
  "CHAMPAGNE",
  "CHAMPAGNE ARABIC",
  "CHAMPAGNE DIAMOND",
  "CHAMPAGNE DIAMOND/RUBY",
  "CHAMPAGNE FLUTED",
  "CHAMPAGNE JUBILEE DIAMOND",
  "CHAMPAGNE LINEN",
  "CHAMPAGNE MOP ROMAN",
  "CHAMPAGNE PALM MOTIF",
  "CHAMPAGNE ROMAN",
  "CHAMPAGNE/BLACK",
  "CHARCOAL",
  "CHOCO/BLACK",
  "CHOCOLATE",
  'CHOCOLATE "VI" DIAMOND',
  "CHOCOLATE ARABIC",
  "CHOCOLATE DIAGONAL MOTIF",
  "CHOCOLATE DIAMOND",
  "CHOCOLATE FLOWER 6 9 DIAMOND",
  "CHOCOLATE JUBILEE DIAMOND",
  "CHOCOLATE MOP ROMAN",
  "CHOCOLATE ROMAN",
  "CHOCOLATE STAR DIAMOND",
  "COKE",
  "CORAL RED",
  "CUSTOM BLACK DIAMOND",
  "CUSTOM CHAMP DIAMOND",
  "CUSTOM MOP DIAMOND",
  "CORNFLOWER BLUE 44 DIAMOND",
  "D-BLUE",
  "DARK GREY",
  "DARK GREY DIAMOND",
  "DARK GREY FLOWER",
  "DARK GREY ROMAN",
  "DARK MOP ROMAN",
  "DARK RHODIUM",
  'DARK RHODIUM "IV&IX" DIAMOND',
  'DARK RHODIUM "VI&IX" DIAMOND',
  "DARK RHODIUM DIAMOND",
  "DARK RHODIUM FLOWER",
  "DARY GREY “VI” DIAMOND",
  "EISENKIESEL DIAMOND",
  "ENAMEL",
  "EXPLORER",
  "FALCON EYE",
  "GMT BAKELITE",
  "GOLDEN",
  "GREEN",
  "GREEN DIAMOND",
  "GREEN FLORAL",
  "GREEN PALM",
  "GREEN ROMAN",
  'GREEN "VI" DIAMOND',
  'GREEN "VI&IX" DIAMOND',
  "GREY",
  "GREY ARABIC",
  "GREY DIAMOND",
  "GREY GREEN ROMAN",
  "GREEN OMBRE ROMAN",
  "HULK",
  "ICE BLUE",
  "ICE BLUE ARABIC",
  "ICE BLUE DIAMOND",
  "ICE BLUE ROMAN",
  "ICE BLUE ROMAN CONCENTRIC",
  "IVORY",
  "IVORY ARABIC",
  "IVORY DIAMOND",
  "IVORY PYRAMID ROMAN",
  "IVORY ROMAN",
  "IVORY JUBILEE",
  "ICE BLUE PAVE INDEX",
  "JAMES BOND",
  "KERMIT",
  "LAVENDER",
  "LIGHT BROWN",
  "LIGHT BROWN RUBBER",
  "LEOPARD DIAMOND",
  "METEORITE",
  "METEORITE DIAMOND",
  "METEORITE ROMAN",
  "MOP",
  "MOP ARABIC",
  "MOP ROMAN",
  "MINT GREEN",
  "MOP DIAMOND",
  "OLIVE GREEN",
  "ORANGE",
  "OLIVE GREEN ROMAN",
  "ONYX DIAMOND",
  "OLIVE GREEN DIAMOND",
  "OLIVE GREEN “VI” DIAMOND",
  "OLIVE GREEN “VI&IX” DIAMOND",
  "PANDA",
  "PAUL NEWMAN",
  "PAVE DIAMOND",
  "PAVE DIAMOND ARABIC",
  "PEPSI",
  "PINK",
  'PINK "VI&IX" DIAMOND',
  "PINK CONCENTRIC ARABIC",
  "PINK DIAMOND",
  "PINK DIAMOND ROMAN",
  "PINK FLORAL MOTIF ARABIC",
  "PINK JUBILEE DIAMOND",
  "PINK OPAL DIAMOND",
  "PINK ROMAN",
  "PINK 6-9 DIAMOND",
  "PINK STAR DIAMOND",
  "PLATINUM",
  "PURPLE",
  'PURPLE "VI&IX" DIAMOND',
  'PURPLE "VI" DIAMOND',
  "PURPLE CAROUSEL DIAMOND",
  "PURPLE DIAMOND",
  "RED",
  "RED ARABIC",
  "RED GRAPE",
  "RHODIUM",
  "RHODIUM 6 9 DIAMOND",
  "RHODIUM DIAMOND",
  "RHODIUM ROMAN",
  "ROOT BEER",
  "ROSE",
  "ROSE ROMAN",
  "RAIL",
  "SALMON",
  "SALMON ROMAN",
  "SERTI",
  "SILVER",
  'SILVER "VI&IX" DIAMOND',
  "SILVER ARABIC",
  "SILVER ARABIC CONCENTRIC",
  "SILVER BLUE ARABIC",
  "SILVER DIAMOND",
  "SILVER DIAMOND ARABIC",
  "SILVER DIAGONAL",
  "SILVER FLUTED",
  "SILVER FLUTED DIAMOND",
  "SILVER FLORAL",
  "SILVER FLOWER ARABIC",
  "SILVER JUBILEE DIAMOND",
  "SILVER LINEN",
  "SILVER PALM DIAMOND",
  "SILVER ROMAN",
  "SILVER TUXEDO",
  "SKELETON",
  "SLATE",
  "SLATE DIAMOND",
  "SLATE FLUTED",
  "SLATE FLUTED DIAMOND",
  "SLATE GREEN ROMAN",
  "SLATE GREY",
  'SLATE "VI&IX" DIAMOND',
  "SPRITE",
  "STARBUCKS",
  "STEEL",
  "STEEL ROMAN",
  "STEEL/BLACK",
  "SUNDUST",
  "SUNDUST DIAMOND",
  "SUNDUST ROMAN",
  "SUNDUST/BLACK",
  "SNOOPY",
  "SMURF",
  "SILVER “VI” DIAMOND",
  "SLATE OMBRE ROMAN",
  "SLATE “VI” DIAMOND",
  "SILVER STAR DIAMOND",
  "SILVER PALM",
  "TIFFANY",
  "TIFFANY BREGUET",
  "TIGER EYE",
  "TURQUOISE",
  "TURQUOISE ROMAN",
  "TURN-O-GRAPH",
  "TUXEDO",
  "WHITE",
  "WHITE & BLACK",
  "WHITE ARABIC",
  "WHITE DIAMOND",
  "WHITE DIAMOND ARABIC",
  "WHITE MOP DIAMOND",
  "WHITE MOP ROMAN",
  "WHITE MOP VI DIAMOND",
  "WHITE ROMAN",
  "WHITE ROMAN DIAMOND",
  "WIMBLEDON",
  "WHITE MOP EMERALDS",
  "YELLOW",
  "YELLOW MOP ROMAN",
  "CHAMPAGNE STAR DIAMOND",
  "ZEBRA DIAMOND",
  "BRUCE WAYNE",
  "JADE RUBY DIAMOND",
  "PAVE DIAMOND ROMAN",
  "MALACHITE “VI&IX” DIAMOND",
  "LAVENDER DIAMOND",
  "LAVENDER",
].sort((a, b) => a.localeCompare(b));

export const boxDropdown = [
  "Blank",
  "N/A",
  "INCLUDED",
  `+ $100`,
  `+ $150`,
  `+ $200`,
  `+ $250`,
  `+ $300`,
  `+ $350`,
  `+ $400`,
  `+ $450`,
  `+ $500`,
];

export const strapDropdown = [
  "Blank",
  "BLACK",
  "BLACK CALFSKIN",
  "BLACK CROCODILE",
  "BLACK LEATHER",
  "BLACK PVD",
  "BLACK RUBBER",
  "BLUE CALFSKIN",
  "BLUE CROCODILE",
  "BLUE FABRIC",
  "BLUE LEATHER",
  "BLUE RUBBER",
  "BLUE SATIN",
  "BEIGE CALFSKIN",
  "BROWN CALFSKIN",
  "BROWN CROCODILE",
  "BROWN LEATHER",
  "BROWN RUBBER",
  "BROWN SATIN",
  "BLACK FABRIC",
  "CERAMIC",
  "CUSTOM DIAMOND",
  "CAMOUFLAGE RUBBER",
  "FROSTED WHITE GOLD",
  "GOLD/STEEL",
  "GREEN CALFSKIN",
  "GREEN CROCODILE",
  "GREEN RUBBER",
  "GREY CROCODILE",
  "GREY RUBBER",
  "GREEN FABRIC",
  "JUBILEE",
  "LEOPARD",
  "LIGHT BROWN RUBBER",
  "LIGHT GREY RUBBER",
  "MASTERPIECE",
  "MULTIPLE STRAPS",
  "N/A",
  "NONE",
  "ORANGE RUBBER",
  "OYSTER",
  "ORANGE CROCODILE",
  "PAVE DIAMOND",
  "PEARLMASTER",
  "PRESIDENT",
  "PURPLE CALFSKIN",
  "PURPLE CROCODILE",
  "PINK CROCODILE",
  "RED CROCODILE",
  "RED RUBBER",
  "ROSE GOLD",
  "ROSE GOLD/STEEL",
  "RUBBER",
  "STEEL",
  "TEXTILE",
  "TITANIUM",
  "TURQUOISE CROCODILE",
  "TITANIUM/PLATINUM",
  "TURQUOISE LIZARD LEATHER",
  "WHITE CROCODILE",
  "WHITE GOLD",
  "WHITE RUBBER",
  "YELLOW CROCODILE",
  "YELLOW GOLD",
  "YELLOW GOLD/STEEL",
  "YELLOW RUBBER",
  "YELLOW GOLD/ROSE GOLD/WHITE GOLD",
  "YELLOW LIZARD LEATHER",
].sort((a, b) => a.localeCompare(b));

export const conditionDropdown = [
  "Blank",
  "GOOD",
  "VERY GOOD",
  "EXCELLENT",
  "LIKE NEW",
  "NEW",
];

export const numOfLinksDropdown = [
  "Blank",
  "N/A",
  "FULL",
  "INCLUDED",
  "SHORT 1",
  "SHORT 2",
  "SHORT 3",
  "SHORT 4",
  "0 REMOVABLE",
  "1 REMOVABLE",
  "2 REMOVABLE",
  "3 REMOVABLE",
  "4 REMOVABLE",
  "5 REMOVABLE",
  "6 REMOVABLE",
  "7 REMOVABLE",
  "1 SCREWS",
  "2 SCREWS",
  "3 SCREWS",
  "4 SCREWS",
  "5 SCREWS",
  "6 SCREWS",
  "7 SCREWS",
];

export const paperDropdown = [
  "Blank",
  "N/A",
  "CARD",
  "PAPER",
  "E-WARRANTY",
  "ARCHIVE",
];

export const LocDropdown = [
  "Blank",
  "NY",
  "LA",
  "T",
  "BKK",
  "HK",
  "TKY",
  "IT",
  "T/NY",
  "T/BKK",
  "T/HK",
  "T/TKY",
  "T/IT",
  "ZH",
  "T/ZH",
  "R/NY",
  "R/BKK",
  "R/HK",
  "R/TKY",
  "R/IT",
  "R/ZH",
];

export const typeDropdown = [
  "New Watch",
  "Preowned Watch",
  "Preowned Vintage Watch",
  "Bag",
];

export const paperStatusDropdown = [
  "With Watch",
  "T/TKY",
  "R/TKY",
  "T/HK",
  "R/HK",
  "T/BKK",
  "R/BKK",
  "T/ZH",
  "R/ZH",
  "T/NY",
  "R/NY",
  "CV",
  "AD",
  "N/A",
];

export const boxStatusDropdown = [
  "N/A",
  "T/TKY",
  "R/TKY",
  "T/HK",
  "R/HK",
  "T/BKK",
  "R/BKK",
  "T/ZH",
  "R/ZH",
  "T/NY",
  "R/NY",
  "T/CV",
  "T/CLIENT",
  "SPARE",
];

export const staffLocDropdown = ["NY", "BKK", "HK", "TK", "ZH"];

export const productTypeDropdown = [
  "Blank",
  "WATCH (Old Stock)",
  "WATCH (Old Stock/Vintage)",
  "WATCH",
  "WATCH (Vintage)",
  "BAG",
]; // C , A , B
export const newDropdown = ["Blank", "PRE OWNED", "NEW", "NEW SPECIAL"]; //P , N , S

export const nyDropdown = ["Blank", "N", "Y"];
export const naDropdown = ["Blank", "N/A", "Y"];
export const numDropdown = ["Blank", "1", "2", "3", "4", "5"];
export const nyLaDropdown = ["Blank", "NY", "LA", "HK", "BK", "TK", "OL"];
export const statusDropdown = [
  "Available",
  "Sold",
  "To Ship",
  "Move to Archive",
];
export const fromDropdown = [
  "Blank",
  "JAPAN",
  "BKK",
  "SD",
  "NYC",
  "WLW",
  "HK",
  "ZH",
  "-------",
  "BUC",
  "CV",
  "DJ",
  "M",
  "MAR",
  "RES",
];
export const orderDropdown = [
  "WAIT_PAYMENT",
  "PAID",
  "ORDERING",
  "ORDERED",
  "ORDERED_FAIL",
  "SHIPPING",
  "DELIVERED",
  "CANCELED",
  "DELETING",
  "DELETED",
  "RESENDING",
  "RESEND",
];

export const NeworderDropdown = [
  { label: "PENDING", value: "PENDING" },
  { label: "CONFIRM", value: "CONFIRM" },
  { label: "PENDING PAYMENT", value: "PENDING_PAYMENT" },
  { label: "SHIP AND PENDING PAYMENT", value: "SHIP_AND_PENDING_PAYMENT" },
  { label: "PAID", value: "PAID" },
  { label: "PAID AND SHIP", value: "PAID_AND_SHIP" },
  { label: "COMPLETE", value: "COMPLETE" },
  { label: "CANCELED", value: "CANCELED" },
];
export const videoDropdown = ["Blank", "MOV", "MP4", "N"]; // Y, M, N

export const newModulesPermissions = [
  {
    moduleName: "inventory-in-stock",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "inventory-sold-pending",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "online-orders",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "inventory-sold-completed",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "inventory-cost",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "box-inventory",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "price-finder",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "stock-replacement",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "wish-list",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "create-package",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "package-history",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "shipping-package",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "share-inventory",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "analysis",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "statistic",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "log-file",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "customers",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "export-csv",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  // {
  //   moduleName: "retail-inventory",
  //   isView: false,
  //   isEdit: false,
  //   subModules: [],
  // },
  {
    moduleName: "settings",
    isView: false,
    isEdit: false,
    subModules: [
      {
        moduleName: "general-setting",
        isView: false,
        isEdit: false,
      },
      {
        moduleName: "commision-report",
        isView: false,
        isEdit: false,
      },
      {
        moduleName: "staff",
        isView: false,
        isEdit: false,
      },
      {
        moduleName: "activity-log",
        isView: false,
        isEdit: false,
      },
      {
        moduleName: "vintage",
        isView: false,
        isEdit: false,
      },
      {
        moduleName: "price-display-config",
        isView: false,
        isEdit: false,
      },
    ],
  },
];

export const newMasterLuxuryModulesPermissions = [
  {
    moduleName: "inventory-in-stock",
    isView: false,
    isEdit: false,
    // isPriceEdit: false,
    subModules: [],
  },
  {
    moduleName: "inventory-sold-pending",
    isView: false,
    isEdit: false,
    // isPriceEdit: false,
    subModules: [],
  },
  {
    moduleName: "inventory-sold-completed",
    isView: false,
    isEdit: false,
    // isPriceEdit: false,
    subModules: [],
  },
  {
    moduleName: "analysis",
    isView: false,
    isEdit: false,
    // isPriceEdit: false,
    subModules: [],
  },
  {
    moduleName: "inventory-retail-price",
    isView: false,
    isEdit: false,
    subModules: [],
  },
  {
    moduleName: "export-csv",
    isView: false,
    isEdit: false,
    subModules: [],
  },
];

export const roleOptions = ["SUPER_ADMIN", "ADMIN", "STAFF"];

export const genderOptions = ["Men's/Unisex", "Women's/Unisex"];

export const movementOptions = ["Automatic", "Manual", "Quartz"];

export const caseShapeOptions = [
  "Round",
  "Cushion",
  "Octagonal",
  "Tonneau",
  "Square",
  "Rectangular",
  "Oval",
].sort((a, b) => a.localeCompare(b));

export const crystalMaterialOptions = [
  "Acrylic Crystal",
  "Hesalite Crystal",
  "Plexiglass",
  "Sapphire Crystal",
].sort((a, b) => a.localeCompare(b));

export const caseBackOptions = ["Solid", "Transparent"];

export const bezelOptions = ["Fixed", "Rotating"];

export const claspStyleOptions = ["Buckle", "Folding Clasp"];

export const hourMarkersOptions = [
  "Arabic Numerals",
  "Roman Numerals",
  "No Numerals",
  "Diamonds",
  "Sapphires",
  "Rubies",
  "Diamonds/Rubies",
].sort((a, b) => a.localeCompare(b));

export const powerReserveOptions = [
  "N/A",
  "35 Hours",
  "38 Hours",
  "40 Hours",
  "42 Hours",
  "44 Hours",
  "45 Hours",
  "48 Hours",
  "50 Hours",
  "52 Hours",
  "55 Hours",
  "60 Hours",
  "65 Hours",
  "66 Hours",
  "70 Hours",
  "72 Hours",
];

export const caseMaterialOptions = [
  "Ceramic",
  "Carbon Fiber",
  "Platinum",
  "Titanium",
  "Steel",
  "Rose Gold",
  "White Gold",
  "Yellow Gold",
  "Rose Gold with Diamonds",
  "White Gold with Diamonds",
  "Yellow Gold with Diamonds",
  "Rose Gold with Gems",
  "White Gold with Gems",
  "Yellow Gold with Gems",
  "Rose Gold/Steel",
  "White Gold/Steel",
  "Yellow Gold/Steel",
  "Rose Gold/White Gold",
].sort((a, b) => a.localeCompare(b));

export const bezelMaterialOptions = [
  "Aluminium",
  "Ceramic",
  "Carbon Fiber",
  "Platinum",
  "Titanium",
  "Steel",
  "Rose Gold",
  "White Gold",
  "Yellow Gold",
  "Rose Gold with Diamonds",
  "White Gold with Diamonds",
  "Yellow Gold with Diamonds",
  "Rose Gold with Gems",
  "White Gold with Gems",
  "Yellow Gold with Gems",
].sort((a, b) => a.localeCompare(b));

export const braceletColorOptions = [
  "N/A",
  "Beige",
  "Black",
  "Blue",
  "Brown",
  "Blue Camouflage",
  "Camouflage",
  "Champagne",
  "Dark Grey",
  "Green",
  "Multi-Color",
  "Orange",
  "Pink",
  "Purple",
  "Red",
  "Silver",
  "Slate Grey",
  "Taupe",
  "Platinum",
  "Rose Gold",
  "Rose Gold/Steel",
  "Steel",
  "Steel/Yellow Gold",
  "Titanium",
  "White",
  "White Gold",
  "Yellow",
  "Yellow Gold",
  "Yellow Gold/Steel",
  "Rose Gold/White Gold",
].sort((a, b) => a.localeCompare(b));

export const dialColorOptions = [
  "ArgentÃ©",
  "Beige",
  "Black",
  "Black Meteorite",
  "Black Mother-of-Pearl",
  "Black/Champagne",
  "Blue",
  "Blue Sodalite",
  "Bronze",
  "Brown",
  "Butterfly",
  "Blue Camouflage",
  "Candy Pink",
  "Camouflage",
  "Carbon Fiber",
  "Champagne Linen",
  "Champagne",
  "Champagne/Black",
  "Chocolate",
  "CloisonnÃ© Enamel Center",
  "Cream",
  "D-Blue",
  "Dark Grey",
  "Slate Grey",
  "Eisenkiesel",
  "Falcon's eye",
  "Onyx",
  "Orange",
  "Ice Blue",
  "Grey",
  "Green",
  "Mint Green",
  "Olive Green",
  "Ivory",
  "Metoerite",
  "Mother-of-Pearl",
  "Pink",
  "Pink Mother-of-Pearl",
  "Purple",
  "Pave Diamond",
  "Platinum",
  "White",
  "White Mother-of-Pearl",
  "Silver Tuxedo",
  "Silver",
  "Skeleton",
  "Sundust",
  "Taupe",
  "Rose",
  "Red",
  "Red Grape",
  "White Grape",
  "Wimbledon",
  "Salmon",
  "Turquoise",
  'Turquoise with "Celebration" motif',
  "Batman",
  "Pepsi",
  "Coke",
  "Sprite",
  "Bruce Wayne",
  "Root Beer",
  "Kermit",
  "Hulk",
  "Starbucks",
].sort((a, b) => a.localeCompare(b));

export const braceletMaterialOptions = [
  "Crocodile",
  "Calfskin",
  "Rubber",
  "Leather",
  "Fabric",
  "Satin",
  "Steel",
  "Rose Gold",
  "White Gold",
  "Yellow Gold",
  "Platinum",
  "Titanium",
  "Ceramic",
  "Rose Gold/Steel",
  "Yellow Gold/Steel",
  "Rose Gold/White Gold",
].sort((a, b) => a.localeCompare(b));

export const waterResistanceOptions = [
  "N/A",
  "30 Meters",
  "50 Meters",
  "60 Meters",
  "100 Meters",
  "120 Meters",
  "150 Meters",
  "300 Meters",
  "1,200 Meters",
  "1,220 Meters",
  "3,900 Meters",
  "11,000 Meters",
];

export const watchLocationDropdown = ["HK", "US", "ZH", "TH"];

export const clientLocationDropdown = ["US", "TH", "OTHER"];

export const pickupLocationDropdown = ["HK", "US", "TH", "ZH", "OTHER"];

// THL0070662

// maximum amount applicable for discount*

// dropdown****
// paper
// # of links
// mongodb
// e2ovbzHrD6sgDe1C

// admin@mlawatches.com

// same font size arial 10
// heigh size of cell
// fixed size of columns

// order status
// Pending
// Confirm
// Ship
// Paid

// export const strapDropdown = [
//   "Blank",
//   "MULTIPLE STRAPS",
//   "BLACK",
//   "MASTERPIECE",
//   "BLACK PVD",
//   "BLACK RUBBER",
//   "BLUE CROCODILE",
//   "BLUE LEATHER",
//   "BLUE RUBBER",
//   "BLUE SATIN",
//   "BLACK CROCODILE",
//   "BROWN CROCODILE",
//   "BROWN LEATHER",
//   "BROWN RUBBER",
//   "BROWN SATIN",
//   "BROWN CALFSKIN",
//   "CERAMIC",
//   "CUSTOM DIAMOND",
//   "GOLD/STEEL",
//   "GREY CROCODILE",
//   "GREY RUBBER",
//   "GREEN CROCODILE",
//   "GREEN RUBBER",
//   "JUBILEE",
//   "LIGHT GREY RUBBER",
//   "FROSTED WHITE GOLD",
//   "NONE",
//   "ORANGE RUBBER",
//   "OYSTER",
//   "PEARLMASTER",
//   "TURQUOISE CROCODILE",
//   "WHITE CROCODILE",
//   "PRESIDENT",

//   "ROSE GOLD",
//   "RED CROCODILE",
//   "RUBBER",
//   "ROSE GOLD/STEEL",

//   "STEEL",

//   "TEXTILE",
//   "TITANIUM",

//   "YELLOW GOLD/STEEL",
//   "WHITE GOLD",
//   "WHITE RUBBER",
//   "WHITE CROCODILE",
//   "YELLOW GOLD",
//   "YELLOW CROCODILE",
//   "N/A",
// ];

// export const dialDropdown = [
//   "Blank",
//   "BATMAN",
//   "BLACK",
//   "BLACK ARABIC",
//   "BLACK ARABIC CONCENTRIC",
//   "BLACK DIAMOND",
//   "BLACK DIAMOND/RUBY",
//   "BLACK MOP DIAMOND",
//   "BLACK MOP ROMAN",
//   "BLACK JUBILEE ARABIC",
//   "BLACK JUBILEE DIAMOND",
//   "BLACK JUBILEE ROMAN",
//   "BLACK ROMAN",
//   "BLACK ROMAN 9 STICK",
//   "BLACK SUNBEAM ROMAN",
//   "BLACK/BLUE",
//   "BLACK/CHAMPAGNE",
//   "BLACK DIAGONAL MOTIF",
//   "BLUE",
//   "BLUE ARABIC",
//   "BLUE CONCENTRIC ARABIC",
//   "BLUE DIAMOND",
//   "BLUE FLUTED",
//   "BLUE FLOWER DIAMOND",
//   "BLUE JUBILEE DIAMOND",
//   "BLUE ROMAN",
//   "BLUE WAVE ARABIC",
//   "BRONZE FLOWER",
//   "BRONZE VI DIAMOND",
//   "BROWN",
//   "BROWN FLOWER",
//   "BROWN NIPPLE",
//   "CANDY PINK",
//   "CARBON FIBER",
//   "CHAMPAGNE",
//   "CHAMPAGNE/BLACK",
//   "CHAMPAGNE ARABIC",
//   "CHAMPAGNE DIAMOND",
//   "CHAMPAGNE DIAMOND/RUBY",
//   "CHAMPAGNE FLUTED",
//   "CHAMPAGNE LINEN",
//   "CHAMPAGNE JUBILEE DIAMOND",
//   "CHAMPAGNE MOP ROMAN",
//   "CHAMPAGNE ROMAN",
//   "CHAMP SUNBEAM ROMAN",
//   "CHAMP TAPESTRY",
//   "CHAMP TUXEDO",
//   "CHARCOAL",
//   "CHOCOLATE",
//   "CHOCOLATE ARABIC",
//   "CHOCO/BLACK",
//   "CHOCOLATE STAR DIAMOND",
//   "CHOCOLATE DIAMOND",
//   "CHOCOLATE FLOWER 6 9 DIAMOND",
//   "CHOCOLATE JUBILEE DIAMOND",
//   "CHOCOLATE ROMAN",
//   "CHOCOLATE MOP ROMAN",
//   'CHOCOLATE "VI" DIAMOND',
//   "CHOCOLATE DIAGONAL MOTIF",
//   "CUSTOM BLACK DIAMOND",
//   "CUSTOM CHAMP DIAMOND",
//   "CUSTOM MOP DIAMOND",
//   "COKE",
//   "CORAL RED",
//   "D-BLUE",
//   "DARK GREY",
//   "DARK GREY DIAMOND",
//   "DARK GREY ROMAN",
//   "DARK GREY FLOWER",
//   "DARK MOP ROMAN",
//   "DARK RHODIUM",
//   'DARK RHODIUM "IV&IX" DIAMOND',
//   "DARK RHODIUM FLOWER",
//   "ENAMEL",
//   "EISENKIESEL DIAMOND",
//   "GOLDEN",
//   "CHAMPAGNE PALM MOTIF",
//   "GREEN",
//   "GREEN DIAMOND",
//   "GREEN FLOWER DIAMOND",
//   "GREEN PALM",
//   "GREEN ROMAN",
//   'GREEN "VI" DIAMOND',
//   'GREEN "VI&IX" DIAMOND',
//   "GREY",
//   "GREY ARABIC",
//   "GREY DIAMOND",
//   "GREY GREEN ROMAN",
//   "HULK",
//   "ICE BLUE",
//   "ICE BLUE ARABIC",
//   "ICE BLUE DIAMOND",
//   "ICE BLUE ROMAN",
//   "ICE BLUE ROMAN CONCENTRIC",
//   "IVORY",
//   "IVORY ARABIC",
//   "IVORY DIAMOND",
//   "IVORY PYRAMID ROMAN",
//   "IVORY ROMAN",
//   "KERMIT",
//   "LIGHT BROWN",
//   "LIGHT BROWN RUBBER",
//   "METEORITE",
//   "METEORITE DIAMOND",
//   "METEORITE ROMAN",
//   "MOP ROMAN",
//   "OLIVE GREEN",
//   "ORANGE",
//   "PANDA",
//   "PAUL NEWMAN",
//   "PAVE DIAMOND",
//   "PEPSI",
//   "PINK",
//   "PINK CONCENTRIC ARABIC",
//   "PINK DIAMOND",
//   "PINK DIAMOND ROMAN",
//   "PINK JUBILEE DIAMOND",
//   "PINK FLORAL MOTIF ARABIC",
//   "PINK ROMAN",
//   "PINK 6-9 DIAMOND",
//   "PLATINUM",
//   "PURPLE",
//   'PURPLE "VI" DIAMOND',
//   'PURPLE "IV&IX" DIAMOND',
//   "RED",
//   "RED GRAPE",
//   "RHODIUM",
//   "RHODIUM DIAMOND",
//   "RHODIUM ROMAN",
//   "RHODIUM 6 9 DIAMOND",
//   "ROOT BEER",
//   "ROSE",
//   "ROSE ROMAN",
//   "SALMON",
//   "SALMON ROMAN",
//   "SERTI",
//   "SKELETON",
//   "SLATE",
//   "SLATE GREY",
//   "SLATE GREEN ROMAN",
//   "SLATE DIAMOND",
//   "SLATE FLUTED",
//   'SILVER "VI" DIAMOND',
//   'SLATE "VI&IX" DIAMOND',
//   "SILVER",
//   "SILVER ARABIC CONCENTRIC",
//   "SILVER BLUE ARABIC",
//   "SILVER DIAMOND",
//   "SILVER DIAGONAL",
//   "SILVER LINEN",
//   "SILVER FLOWER ARABIC",
//   "SILVER FLOWER",
//   "SILVER FLUTED",
//   "SILVER FLUTED DIAMOND",
//   "SILVER JUBILEE DIAMOND",
//   "SILVER PALM DIAMOND",
//   "SILVER ROMAN",
//   "SILVER TUXEDO",
//   'SILVER "VI&IX" DIAMOND',
//   "SPRITE",
//   "STEEL",
//   "STEEL ROMAN",
//   "STEEL/BLACK",
//   "SUNDUST/BLACK",
//   "SUNDUST",
//   "SUNDUST DIAMOND",
//   "SUNDUST ROMAN",
//   "TURQUOISE ROMAN",
//   "TIFFANY",
//   "TIGER EYE",
//   "TUXEDO",
//   "WHITE",
//   "WHITE ARABIC",
//   "WHITE & BLACK",
//   "WHITE DIAMOND",
//   "WHITE DIAMOND ARABIC",
//   "WHITE MOP DIAMOND",
//   "WHITE MOP ROMAN",
//   'WHITE MOP "VI" DIAMOND',
//   "WHITE ROMAN",
//   "WHITE ROMAN DIAMOND",
//   "YELLOW",
//   "YELLOW MOP ROMAN",
//   "TIFFANY BREGUET",
//   "EXPLORER",
//   "WIMBLEDON",
//   "TURN-O-GRAPH",
//   "JAMES BOND",
//   "AUTAVIA",
//   "GMT BAKELITE",
//   "STARBUCKS",
//   "BLUE SODALITE DIAMOND",
//   'DARK RHODIUM "VI&IX" DIAMOND',
//   'PINK "VI&IX" DIAMOND',
//   "DARK RHODIUM DIAMOND",
//   "TURQUOISE",
//   "TURQUOISE ROMAN",
//   "PAVE DIAMOND ARABIC",
// ];

export const materialDropDown = [
  "SS",
  "YG",
  "RG",
  "WG",
  "PL",
  "BZ",
  "CE",
  "CF",
  "TI",
  "SS/RG",
  "SS/YG",
  "SS/WG",
  "SS/PL",
  "WG/RG",
].sort((a, b) => a.localeCompare(b));

export const braceletDropDownForShipCal = [
  "Strap(Rubber/Leather/Fabric)",
  "Bracelet for PO",
  "Bracelet for NEW",
];

export const purchaseCurrencyDropDown = ["EU", "HKD", "JPY", "THB", "GBP"];
